spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/app_database
    username: user
    password: password
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true